/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViolationsRouteImport } from './routes/violations'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreativesRouteImport } from './routes/creatives'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManageIndexRouteImport } from './routes/manage.index'
import { Route as ManageCampaignIdRouteImport } from './routes/manage.$campaignId'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns.$campaignId'

const ViolationsRoute = ViolationsRouteImport.update({
  id: '/violations',
  path: '/violations',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreativesRoute = CreativesRouteImport.update({
  id: '/creatives',
  path: '/creatives',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageIndexRoute = ManageIndexRouteImport.update({
  id: '/manage/',
  path: '/manage/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageCampaignIdRoute = ManageCampaignIdRouteImport.update({
  id: '/manage/$campaignId',
  path: '/manage/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/campaigns/$campaignId',
  path: '/campaigns/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/creatives': typeof CreativesRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/violations': typeof ViolationsRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/manage/$campaignId': typeof ManageCampaignIdRoute
  '/manage/': typeof ManageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/creatives': typeof CreativesRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/violations': typeof ViolationsRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/manage/$campaignId': typeof ManageCampaignIdRoute
  '/manage': typeof ManageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/creatives': typeof CreativesRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/violations': typeof ViolationsRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/manage/$campaignId': typeof ManageCampaignIdRoute
  '/manage/': typeof ManageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/creatives'
    | '/dashboard'
    | '/jobs'
    | '/violations'
    | '/campaigns/$campaignId'
    | '/manage/$campaignId'
    | '/manage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/creatives'
    | '/dashboard'
    | '/jobs'
    | '/violations'
    | '/campaigns/$campaignId'
    | '/manage/$campaignId'
    | '/manage'
  id:
    | '__root__'
    | '/'
    | '/creatives'
    | '/dashboard'
    | '/jobs'
    | '/violations'
    | '/campaigns/$campaignId'
    | '/manage/$campaignId'
    | '/manage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreativesRoute: typeof CreativesRoute
  DashboardRoute: typeof DashboardRoute
  JobsRoute: typeof JobsRoute
  ViolationsRoute: typeof ViolationsRoute
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRoute
  ManageCampaignIdRoute: typeof ManageCampaignIdRoute
  ManageIndexRoute: typeof ManageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/violations': {
      id: '/violations'
      path: '/violations'
      fullPath: '/violations'
      preLoaderRoute: typeof ViolationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creatives': {
      id: '/creatives'
      path: '/creatives'
      fullPath: '/creatives'
      preLoaderRoute: typeof CreativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/': {
      id: '/manage/'
      path: '/manage'
      fullPath: '/manage/'
      preLoaderRoute: typeof ManageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/$campaignId': {
      id: '/manage/$campaignId'
      path: '/manage/$campaignId'
      fullPath: '/manage/$campaignId'
      preLoaderRoute: typeof ManageCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreativesRoute: CreativesRoute,
  DashboardRoute: DashboardRoute,
  JobsRoute: JobsRoute,
  ViolationsRoute: ViolationsRoute,
  CampaignsCampaignIdRoute: CampaignsCampaignIdRoute,
  ManageCampaignIdRoute: ManageCampaignIdRoute,
  ManageIndexRoute: ManageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
